// ---- Edit this file to add/change fixtures. No other file needs to change. ----

const MATCHES = [
  {
    slug: "argentina-switzerland",
    home: "Argentina", away: "Switzerland",
    homeAbbr: "ARG", awayAbbr: "SUI",
    homeColor: "#75AADB", awayColor: "#D52B1E",
    group: "Group C", stadium: "MetLife Stadium, New Jersey",
    date: "Jun 14, 2026", time: "9:00 PM ET",
    status: "upcoming",
    summary: "Defending champions Argentina open their title defense against a disciplined Switzerland side known for its structured, low-block defending.",
    channel: "FOX Sports",
    matchType: "Group Stage",
    watchLink: "watch-live.html?match=argentina-switzerland&team=home",
    channelInfo: {
      team: "Argentina",
      region: "Argentina",
      satellite: "ARSAT-1",
      channelName: "Public TV",
      frequency: "11670 V",
      symbolRate: "30000",
      encryption: "Free to air",
      language: "Spanish",
      backupChannel: "TyC Sports",
      note: "Argentina viewers can follow the match through national sports coverage. Channel availability can vary by provider, so check your local TV guide before kickoff.",
      broadcastLinks: [
        { label: "Link 1: Argentina vs Switzerland", url: "live-broadcast.html?match=argentina-switzerland&server=1", description: "SportsHub stream server 1" },
        { label: "Link 2: Argentina vs Switzerland", url: "live-broadcast.html?match=argentina-switzerland&server=2", description: "SportsHub stream server 2" },
        { label: "Link 3: Argentina vs Switzerland", url: "live-broadcast.html?match=argentina-switzerland&server=3", description: "SportsHub stream server 3" },
        { label: "Link 4: Argentina vs Switzerland", url: "live-broadcast.html?match=argentina-switzerland&server=4", description: "SportsHub stream server 4" }
      ]
    },
    homeLineup: "Martinez, Molina, Romero, Otamendi, Tagliafico, De Paul, Fernandez, Mac Allister, Messi, Alvarez, Di Maria",
    awayLineup: "Sommer, Widmer, Akanji, Schar, Rodriguez, Xhaka, Freuler, Shaqiri, Sow, Vargas, Embolo",
  },
  {
    slug: "norway-england",
    home: "Norway", away: "England",
    homeAbbr: "NOR", awayAbbr: "ENG",
    homeColor: "#EF2B2D", awayColor: "#1E3A8A",
    group: "Group B", stadium: "Lincoln Financial Field, Philadelphia",
    date: "Jun 14, 2026", time: "6:00 PM ET",
    status: "live",
    summary: "Norway's Haaland-led attack meets an England side rebuilding around a new generation of midfielders after a shaky qualifying campaign.",
    channel: "BBC Sport",
    matchType: "Group Stage",
    watchLink: "watch-live.html?match=norway-england&team=home",
    channelInfo: {
      team: "Norway",
      region: "Norway",
      satellite: "Thor 5",
      channelName: "NRK",
      frequency: "11325 H",
      symbolRate: "24500",
      encryption: "Free to air",
      language: "Norwegian",
      backupChannel: "TV 2 Sport",
      note: "Norway viewers can follow the match through national sports coverage. Channel availability can vary by provider, so check your local TV guide before kickoff.",
      broadcastLinks: [
        { label: "Link 1: Norway vs England", url: "live-broadcast.html?match=norway-england&server=1", description: "SportsHub stream server 1" },
        { label: "Link 2: Norway vs England", url: "live-broadcast.html?match=norway-england&server=2", description: "SportsHub stream server 2" },
        { label: "Link 3: Norway vs England", url: "live-broadcast.html?match=norway-england&server=3", description: "SportsHub stream server 3" },
        { label: "Link 4: Norway vs England", url: "live-broadcast.html?match=norway-england&server=4", description: "SportsHub stream server 4" }
      ]
    },
    homeLineup: "Nyland, Ryerson, Ajer, Ostigard, Meling, Berge, Odegaard, Aursnes, Sorloth, Haaland, Nusa",
    awayLineup: "Pickford, Walker, Stones, Guehi, Shaw, Rice, Bellingham, Foden, Saka, Kane, Rashford",
  },
  {
    slug: "spain-belgium",
    home: "Spain", away: "Belgium",
    homeAbbr: "ESP", awayAbbr: "BEL",
    homeColor: "#AA151B", awayColor: "#FDDA24",
    group: "Group D", stadium: "AT&T Stadium, Dallas",
    date: "Jun 15, 2026", time: "3:00 PM ET",
    status: "upcoming",
    summary: "Spain's possession-heavy system faces a Belgian squad in transition, leaning on pace on the counter rather than their golden generation's control.",
    channel: "FOX Sports",
    matchType: "Group Stage",
    watchLink: "watch-live.html?match=spain-belgium&team=home",
    channelInfo: {
      team: "Spain",
      region: "Spain",
      satellite: "Astra 19.2E",
      channelName: "RTVE",
      frequency: "11038 V",
      symbolRate: "22000",
      encryption: "Free to air",
      language: "Spanish",
      backupChannel: "Movistar Plus",
      note: "Spain viewers can follow the match through national sports coverage. Channel availability can vary by provider, so check your local TV guide before kickoff.",
      broadcastLinks: [
        { label: "Link 1: Spain vs Belgium", url: "live-broadcast.html?match=spain-belgium&server=1", description: "SportsHub stream server 1" },
        { label: "Link 2: Spain vs Belgium", url: "live-broadcast.html?match=spain-belgium&server=2", description: "SportsHub stream server 2" },
        { label: "Link 3: Spain vs Belgium", url: "live-broadcast.html?match=spain-belgium&server=3", description: "SportsHub stream server 3" },
        { label: "Link 4: Spain vs Belgium", url: "live-broadcast.html?match=spain-belgium&server=4", description: "SportsHub stream server 4" }
      ]
    },
    homeLineup: "Simon, Carvajal, Le Normand, Laporte, Cucurella, Rodri, Pedri, Merino, Yamal, Morata, Williams",
    awayLineup: "Courtois, Castagne, Faes, Theate, De Cuyper, Onana, Tielemans, De Bruyne, Doku, Lukaku, Trossard",
  },
  {
    slug: "france-morocco",
    home: "France", away: "Morocco",
    homeAbbr: "FRA", awayAbbr: "MAR",
    homeColor: "#0055A4", awayColor: "#C1272D",
    group: "Group A", stadium: "SoFi Stadium, Los Angeles",
    date: "Jun 15, 2026", time: "12:00 PM ET",
    status: "upcoming",
    summary: "A rematch of the 2022 semifinal - France look to avenge nothing, having won that meeting, but Morocco return with a deeper squad.",
    channel: "FOX Sports",
    matchType: "Group Stage",
    watchLink: "watch-live.html?match=france-morocco&team=home",
    channelInfo: {
      team: "France",
      region: "France",
      satellite: "Eutelsat 5 West B",
      channelName: "TF1",
      frequency: "11554 V",
      symbolRate: "29950",
      encryption: "Free to air",
      language: "French",
      backupChannel: "beIN Sports",
      note: "France viewers can follow the match through national sports coverage. Channel availability can vary by provider, so check your local TV guide before kickoff.",
      broadcastLinks: [
        { label: "Link 1: France vs Morocco", url: "live-broadcast.html?match=france-morocco&server=1", description: "SportsHub stream server 1" },
        { label: "Link 2: France vs Morocco", url: "live-broadcast.html?match=france-morocco&server=2", description: "SportsHub stream server 2" },
        { label: "Link 3: France vs Morocco", url: "live-broadcast.html?match=france-morocco&server=3", description: "SportsHub stream server 3" },
        { label: "Link 4: France vs Morocco", url: "live-broadcast.html?match=france-morocco&server=4", description: "SportsHub stream server 4" }
      ]
    },
    homeLineup: "Maignan, Kounde, Upamecano, Saliba, Hernandez, Tchouameni, Camavinga, Griezmann, Dembele, Mbappe, Thuram",
    awayLineup: "Bono, Hakimi, Aguerd, Saiss, Mazraoui, Amrabat, Ounahi, Ziyech, Harit, Boufal, En-Nesyri",
  },
  {
    slug: "switzerland-colombia",
    home: "Switzerland", away: "Colombia",
    homeAbbr: "SUI", awayAbbr: "COL",
    homeColor: "#D52B1E", awayColor: "#FCD116",
    group: "Group C", stadium: "Hard Rock Stadium, Miami",
    date: "Jun 16, 2026", time: "5:00 PM ET",
    status: "upcoming",
    summary: "Colombia's front line looks to break down a Swiss defense that conceded the fewest goals of any European qualifier this cycle.",
    channel: "FOX Sports",
    matchType: "Group Stage",
    watchLink: "watch-live.html?match=switzerland-colombia&team=home",
    channelInfo: {
      team: "Switzerland",
      region: "Switzerland",
      satellite: "Hot Bird 13E",
      channelName: "SRF zwei",
      frequency: "12399 H",
      symbolRate: "27500",
      encryption: "Free to air",
      language: "German",
      backupChannel: "RTS Sport",
      note: "Switzerland viewers can follow the match through national sports coverage. Channel availability can vary by provider, so check your local TV guide before kickoff.",
      broadcastLinks: [
        { label: "Link 1: Switzerland vs Colombia", url: "live-broadcast.html?match=switzerland-colombia&server=1", description: "SportsHub stream server 1" },
        { label: "Link 2: Switzerland vs Colombia", url: "live-broadcast.html?match=switzerland-colombia&server=2", description: "SportsHub stream server 2" },
        { label: "Link 3: Switzerland vs Colombia", url: "live-broadcast.html?match=switzerland-colombia&server=3", description: "SportsHub stream server 3" },
        { label: "Link 4: Switzerland vs Colombia", url: "live-broadcast.html?match=switzerland-colombia&server=4", description: "SportsHub stream server 4" }
      ]
    },
    homeLineup: "Sommer, Widmer, Akanji, Schar, Rodriguez, Xhaka, Freuler, Shaqiri, Sow, Vargas, Embolo",
    awayLineup: "Vargas, Munoz, Sanchez, Lucumi, Mojica, Lerma, Uribe, James, Diaz, Arias, Duran",
  },
  {
    slug: "argentina-egypt",
    home: "Argentina", away: "Egypt",
    homeAbbr: "ARG", awayAbbr: "EGY",
    homeColor: "#75AADB", awayColor: "#CE1126",
    group: "Group C", stadium: "Rose Bowl, Los Angeles",
    date: "Jun 20, 2026", time: "8:00 PM ET",
    status: "upcoming",
    summary: "Egypt make their first World Cup appearance in twelve years and face a stern test against the group favorites.",
    channel: "FOX Sports",
    matchType: "Group Stage",
    watchLink: "watch-live.html?match=argentina-egypt&team=home",
    channelInfo: {
      team: "Argentina",
      region: "Argentina",
      satellite: "ARSAT-1",
      channelName: "Public TV",
      frequency: "11670 V",
      symbolRate: "30000",
      encryption: "Free to air",
      language: "Spanish",
      backupChannel: "TyC Sports",
      note: "Argentina viewers can follow the match through national sports coverage. Channel availability can vary by provider, so check your local TV guide before kickoff.",
      broadcastLinks: [
        { label: "Link 1: Argentina vs Egypt", url: "live-broadcast.html?match=argentina-egypt&server=1", description: "SportsHub stream server 1" },
        { label: "Link 2: Argentina vs Egypt", url: "live-broadcast.html?match=argentina-egypt&server=2", description: "SportsHub stream server 2" },
        { label: "Link 3: Argentina vs Egypt", url: "live-broadcast.html?match=argentina-egypt&server=3", description: "SportsHub stream server 3" },
        { label: "Link 4: Argentina vs Egypt", url: "live-broadcast.html?match=argentina-egypt&server=4", description: "SportsHub stream server 4" }
      ]
    },
    homeLineup: "Martinez, Molina, Romero, Otamendi, Tagliafico, De Paul, Fernandez, Mac Allister, Messi, Alvarez, Di Maria",
    awayLineup: "El Shenawy, Hany, Hegazy, Abdelmonem, Hamdy, Elneny, Hamdi, Trezeguet, Salah, Marmoush, Mostafa Mohamed",
  },
  {
    slug: "usa-belgium",
    home: "USA", away: "Belgium",
    homeAbbr: "USA", awayAbbr: "BEL",
    homeColor: "#B22234", awayColor: "#FDDA24",
    group: "Group D", stadium: "Mercedes-Benz Stadium, Atlanta",
    date: "Jun 21, 2026", time: "7:00 PM ET",
    status: "upcoming",
    summary: "Host nation USA look to build on a strong qualifying run as they face a Belgian side hunting a first group-stage win.",
    channel: "FOX Sports",
    matchType: "Group Stage",
    watchLink: "watch-live.html?match=usa-belgium&team=home",
    channelInfo: {
      team: "USA",
      region: "United States",
      satellite: "Local Cable",
      channelName: "FOX Sports",
      frequency: "Provider dependent",
      symbolRate: "Provider dependent",
      encryption: "Subscription may apply",
      language: "English",
      backupChannel: "Telemundo",
      note: "USA viewers can follow the match through national sports coverage. Channel availability can vary by provider, so check your local TV guide before kickoff.",
      broadcastLinks: [
        { label: "Link 1: USA vs Belgium", url: "live-broadcast.html?match=usa-belgium&server=1", description: "SportsHub stream server 1" },
        { label: "Link 2: USA vs Belgium", url: "live-broadcast.html?match=usa-belgium&server=2", description: "SportsHub stream server 2" },
        { label: "Link 3: USA vs Belgium", url: "live-broadcast.html?match=usa-belgium&server=3", description: "SportsHub stream server 3" },
        { label: "Link 4: USA vs Belgium", url: "live-broadcast.html?match=usa-belgium&server=4", description: "SportsHub stream server 4" }
      ]
    },
    homeLineup: "Turner, Dest, Richards, Ream, Robinson, Adams, McKennie, Musah, Pulisic, Balogun, Weah",
    awayLineup: "Courtois, Castagne, Faes, Theate, De Cuyper, Onana, Tielemans, De Bruyne, Doku, Lukaku, Trossard",
  },
];

const POPULAR_POSTS = [
  { slug: "full-2026-world-cup-fixture-list", title: "Full 2026 World Cup Fixture List & Kickoff Times", meta: "42.1k views" },
  { slug: "group-stage-tiebreakers", title: "How Group Stage Tiebreakers Work This Year", meta: "28.6k views" },
  { slug: "host-city-stadium-guide", title: "Every Host City & Stadium Guide", meta: "19.3k views" },
  { slug: "squad-watch-injuries", title: "Squad Watch: Injuries to Track Before Kickoff", meta: "12.8k views" },
];

const UPCOMING = [
  { teams: "ARG vs SUI", time: "Jun 14" },
  { teams: "NOR vs ENG", time: "Jun 14" },
  { teams: "ESP vs BEL", time: "Jun 15" },
  { teams: "FRA vs MAR", time: "Jun 15" },
  { teams: "SUI vs COL", time: "Jun 16" },
];

const TICKER_ITEMS = [
  "ARG 0-0 SUI - KO 9:00 PM ET",
  "NOR 1-0 ENG - LIVE 34'",
  "ESP vs BEL - Sat 3:00 PM ET",
  "FRA vs MAR - Sat 12:00 PM ET",
  "SUI vs COL - Sun 5:00 PM ET",
  "Group Stage - Matchday 1 underway",
];
